-keep class net.sqlcipher.** { *; }
-keep class chat.fluffy.fluffychat.** { *; }
-keep class org.iquxae.qnskk.** { *; }
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.embedding.** { *; }

-dontwarn com.google.android.play.**
-dontwarn io.flutter.embedding.engine.deferredcomponents.**